name: colbert
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - faiss-gpu
  - pip=21.0
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.3
  - pip:
    - bitarray
    - datasets
    - gitpython
    - jupyter
    - jupyterlab
    - ninja
    - scipy
    - spacy
    - tqdm
    - transformers
    - ujson
